### ISSUE TITLE
Kill_streams docker issue

### ISSUE THREAD

**Issue by modem7** [blacktwin/JBOPS#236]
**Describe the bug**
Getting error in log when calling script

![image](https://user-images.githubusercontent.com/4349962/89817344-e800a380-db3f-11ea-80b1-0b12ffdde487.png)

**Link to script with bug/issue**
https://github.com/blacktwin/JBOPS/blob/master/killstream/kill_stream.py

**To Reproduce**
![image](https://user-images.githubusercontent.com/4349962/89817547-3dd54b80-db40-11ea-8b24-5032ef99d085.png)

Docker compose entry:

```
 #Tautulli - Plex statistics and monitoring
  tautulli:
    image: tautulli/tautulli
    container_name: Tautulli
    hostname: Tautulli
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels: 
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAINNAME`)"
      - "traefik.http.routers.tautulli-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
     # Healthcheck
      - "traefik.http.services.tautulli-svc.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.tautulli-svc.loadbalancer.healthcheck.timeout=3s"
      - "traefik.http.services.tautulli-svc.loadbalancer.healthcheck.path=/"
    networks:
      pihole:
        ipv4_address: '172.22.0.107'
    healthcheck:
      test: ["CMD", "curl", "-sS", "127.0.0.1:8181/tautulli/status"]
      start_period: 60s
      interval: 5s
      retries: 3
    ports:
      - "38069:8181"
    volumes:
      - $USERDIR/Tautulli:/config
      - $USERDIR/Tautulli/scripts:/scripts:ro
      - /home/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    restart: always
    mem_limit: 500m
    mem_reservation: 200m
```

Script put into scripts folder, script has correct read permissions and has been chmod +x

**Expected behavior**
For the session to be killed
